### ISSUE TITLE
user-select

### ISSUE THREAD

**Issue by eskan** [MeTaNoV/iron-swipeable-pages#1]
Hello,
very useful element !
Please let me know why you activate user-select : none as it prevent (for my test on chrome only) fired events and use button in pages. In fact i'm pretty sure i've missed something :D 
thanks,
Cyrille

**Comment by MeTaNoV** [comment]
Hi Ekan (I am too from Lorraine, Longwy! :)
I derive from `iron-selectable-behavior`, that's why!
Is it a problem for you?
Cheers,
Pascal

**Comment by eskan** [comment]
He .. from Metz .. Neighbour ! 

my question is about that part of CSS :    
```
 :host > ::content * {
      pointer-events: none;
      -webkit-user-select: none;  
      -moz-user-select: none;     
      -ms-user-select: none;      
      user-select: none;       
      cursor: default;
 }
```

**Comment by MeTaNoV** [comment]
I gave you the answer! :)

**Comment by eskan** [comment]
I've read another answer you wrote about behaviors ... we are too closed ;)
For now i'm using your SO USEFUL element for mobile to emulate a android view pager, bind to a paper-tabs
There's some issue for that : swipe prevent scrolling page.
I'll keep you in touch and i hope i'll we be able to submit PR :d

**Comment by MeTaNoV** [comment]
Yep, pas de soucis!
