### ISSUE TITLE
Cannot read property 'style' of undefined at _initPage

### ISSUE THREAD

**Issue by rubenstolk** [MeTaNoV/iron-swipeable-pages#16]
In case the items of this elements are dynamic, e.g. by using `dom-if`, `_initPage` fails because a page might be undefined. The following example throws this error:

```html
<iron-swipeable-pages>
  <template is="dom-if" if="[[nothing]]">
    <div>Page 1</div>
  </</template>
  <template is="dom-if" if="[[nothing]]">
    <div>Page 2</div>
  </template>
</iron-swipeable-pages>
```

I've included a simple `if (!page) { return }` in https://github.com/MeTaNoV/iron-swipeable-pages/pull/15 which solves this.

**Comment by MeTaNoV** [comment]
so, I created a demo that I will use to check how it should behave in this case. This will be more tricky than just your PR I think! :)
https://github.com/MeTaNoV/iron-swipeable-pages/blob/master/demo/conditional.html
Tell me if it cover your use-case and start play with it.
I will take care of the fix.

**Comment by rubenstolk** [comment]
Are you encountering the `style of undefined` error?

**Comment by MeTaNoV** [comment]
So, I manage to solve the issue with the `dom-if`s. I added an optional attribute `check-display` that force synchronous update of the items that filters `display=none` element, therefore element under filtered `dom-if` before initiating any swipe action. This way, we have a proper list to work on to set up the animated pages. I hope this also solved your issue with the style. But as I said, it might be worth to try also testing to replace with `iron-pages` to see the behavior!

**Comment by rubenstolk** [comment]
Seems resolved indeed, will re-open if I still find an issue with this.
