### ISSUE TITLE
Vertical scroll interferes with horizontal swipe

### ISSUE THREAD

**Issue by rubenstolk** [MeTaNoV/iron-swipeable-pages#17]
When the pages have an overflow that scrolls, the swipe effect interferes with the vertical scroll which gives an undesired behavior.

This issue can be easily solved by preventing the `touchmove` event while swiping, I'll send a PR for it.

**Comment by MeTaNoV** [comment]
I need to play a bit with this before going further...

**Comment by MeTaNoV** [comment]
@rubenstolk just wanting to know if this could be closed after the integration of `1.2.1`?

**Comment by rubenstolk** [comment]
This has been solved in `1.2.1` indeed.
