### ISSUE TITLE
Too many warning on dom-change

### ISSUE THREAD

**Issue by fleckdalm** [MeTaNoV/iron-swipeable-pages#22]
Since the latest update the component gives me dozens of warnings because of the new conditional templates feature: 
> iron-swipeable-pages: consider using the property forceUpdate since `dom-change` event has been triggered inside the component

As I'm not using any conditional pages this is unnecessary and should be avoided please.

**Comment by MeTaNoV** [comment]
yes, yes yes... I will add more doc related to this, sorry for the inconvenience...

**Comment by fleckdalm** [comment]
No problem and thanks for the great component!

**Comment by MeTaNoV** [comment]
pushed on master, I wait for another feature currently under test to land before releasing `1.2.2`. Should be this evening or tomorrow!
