### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by andregauthier** [MeTaNoV/iron-swipeable-pages#24]
In the '_resetPages' function, sometimes '_animatedPages' is undefined. It happens to me when only 1 page is in the container.

**Comment by MeTaNoV** [comment]
are you using conditional `dom-if`s?

**Comment by MeTaNoV** [comment]
I solved an issue when only one page was configured, are you using the latest version of the component?
that is, is the following code there: https://github.com/MeTaNoV/iron-swipeable-pages/blob/master/iron-swipeable-pages.html#L220

**Comment by MeTaNoV** [comment]
@andregauthier and if you have some code to reproduce, I would be curious to take a look at it! :)

**Comment by MeTaNoV** [comment]
can you test with the latest release? https://github.com/MeTaNoV/iron-swipeable-pages/releases/tag/1.2.2

**Comment by andregauthier** [comment]
I was using the latest release before your last changes. I updated and it now works perfectly. Thanks for the quick answer!

**Comment by MeTaNoV** [comment]
no problem, glad it works now! :)

**Comment by MeTaNoV** [comment]
@andregauthier and if you find the element useful, don't hesitate to star it! (merci d'avance! :) )
