### ISSUE TITLE
iron-overlay-backdrop on top of paper-dialog

### ISSUE THREAD

**Issue by jefhermans** [MeTaNoV/iron-swipeable-pages#25]
If I use iron-swipeable-pages instead of iron-pages, the gray overlay that I get when I open a paper-dialog is shown on top. So the paper-dialog also gets hidden behind the overlay.

**Comment by fleckdalm** [comment]
This happens because of the creation of a new stacking contexts: https://github.com/vaadin/vaadin-date-picker/issues/133 unfortunately there isn't much you can do against this. I circumvent it by manually setting a Css rule 
`body *{will-change: inherit!important;} `
Whenever a dialog is open.

**Comment by jefhermans** [comment]
Thanks, that's indeed a possible solution. It helped me a lot!
I will close the issue.
