### ISSUE TITLE
Make transition between different height pages smoother

### ISSUE THREAD

**Issue by fleckdalm** [MeTaNoV/iron-swipeable-pages#32]
If the pages have a different height and you scroll down to the bottom of the higher page and then switch to the other page, there is some flickering before it finally  appears. This is because the vertical scroll position is shared between the pages. The default behavior (on Android) would be that every page has its own vertical scroll position (you could e.g. take a look at the Facebook app).

**Comment by MeTaNoV** [comment]
good point! this is fixed in master and I also just released 1.2.3.
A live example can be found here: https://metanov.github.io/iron-swipeable-pages/components/iron-swipeable-pages/demo/mobile.html

**Comment by fleckdalm** [comment]
Thanks a lot! You are doing really good work and I totally appreciate your constant improvements to the component :)

**Comment by MeTaNoV** [comment]
You're welcome! It is also very helpful to get feedback from you to help improve it!
