### ISSUE TITLE
Pages stuck when rapid swipe twice or fast

### ISSUE THREAD

**Issue by JohnsonChung** [MeTaNoV/iron-swipeable-pages#34]
Hallo Pascal Gula, sorry to bother you again.
I found an issue when swiping pages that you can check it by below.
[demo](https://youtu.be/gvb8Tc1idXk)
[app](https://youtu.be/cpqky4dzAIo)
This issue particularly happens in the page contain a lot of element ( Maybe 10 ~ 20 up images I'm not sure of that. )

best regard
Johnson

**Comment by MeTaNoV** [comment]
this is fixed in master, I will release a new 1.2.4 version, when I will close 2 ongoing Issue! Thanks for spotting the Issue! :)
