### ISSUE TITLE
Allow touch action

### ISSUE THREAD

**Issue by fleckdalm** [MeTaNoV/iron-swipeable-pages#4]
The default behaviour is touch-action: none; which prevents scrolling vertically on mobile devices. To circumvent this limitations you could just allow touch-action and additionally add this check in _trackMove:

 if(Math.abs(trackData.dx)<75){
            return;//probably swipind down
 }

of course the treshhold value (75) could be adjusted.

**Comment by MeTaNoV** [comment]
This is indeed very valuable! Are you using Cordova for your app?

**Comment by fleckdalm** [comment]
Yes, im using cordova in conjunction with crosswalk so that its even working on older devices.
