### ISSUE TITLE
Allow child element to trigger swipe

### ISSUE THREAD

**Issue by hdicksonjr** [MeTaNoV/iron-swipeable-pages#40]
When a function which changes the selected page is triggered from a page's child element, the page still changes, but the transition is cancelled.

This behavior is not present in releases before e561e5053db9f4af154833cafd4eb5ec0d4d593f was merged.

It should be possible to trigger a page transition from a child element, but if not, the transition should be completely cancelled rather than changing the current page and cancelling the actual transition.

**Comment by MeTaNoV** [comment]
@hdicksonjr should be fixed in master, I am going to release a new version! (BTW, sorry for the delay...)

**Comment by MeTaNoV** [comment]
I am closing, feel free to re-open if the bug is still present!

**Comment by hdicksonjr** [comment]
I'll keep an eye out for the new version. Thanks!

**Comment by MeTaNoV** [comment]
@hdicksonjr BTW, you can also star it, if you find the component useful and want to increase its visibility! :)

**Comment by hdicksonjr** [comment]
@MeTaNoV I fired a couple other questions off to you on the Polymer Slack channel when you get a sec. Not sure how often you check that.
