### ISSUE TITLE
Dynamic content not getting displayed.

### ISSUE THREAD

**Issue by baljeetbhinder** [MeTaNoV/iron-swipeable-pages#49]
Hi I have this code which uses dynamic content on iron swipeable pages

``` javascript
<iron-swipeable-pages selected="0" id='swipePages'>
    <template is="dom-repeat" items=[[data]]>
        <div id="[[item.number]]">
          Some info here...
        </div>
    </template>
</iron-swipeable-pages>
```

It works fine when page loads initially but after that as the `data` gets changed it is not showing the items in view. Any idea how can I bind dynamic content in here?

**Comment by n1ywb** [comment]
It should "just work"; it does on my site. Most likely the changes you are making to the data array are not observable.

Check the contents of your data array in the debugger after you set it to sanity check that it's actually getting set the way you think it is. I was pulling my hair out over a similar issue recently and it was something that simple.

Inspect the properties on the div and template tags to ensure data is actually propagating.

Set an observer on data.0.number and put `console.log("data.0.number changed")` in it (and maybe set a breakpoint) to verify that the changes are observed when you mutate data. I bet it does not. I've found making observable changes to arrays is pretty tricky in Polymer. Be sure you are using the proper array manipulation technique.

See also **https://www.polymer-project.org/1.0/docs/devguide/data-system#observable-changes**

**Comment by MeTaNoV** [comment]
let's close this!
