### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by fleckdalm** [MeTaNoV/iron-swipeable-pages#9]
Adding css like this:
`iron-swipeable-pages > *{
    will-change: left, transform;
}`
greatly improves performance, especially on mobile. I would recommand to add this directly to the component ;)

**Comment by MeTaNoV** [comment]
Thanks, very interesting CSS property I didn't know of! This is definitely a perfect fit to the component. I'll add it!

**Comment by MeTaNoV** [comment]
@fleckdalm you can test it on master, I'll do a release when I'll merge the other opened PR.

**Comment by fleckdalm** [comment]
Thank you!
